name: RubyBukkit
main: org.notbukkit.RubyBukkit
load: startup
author: Zeerix
website: http://forums.bukkit.org/threads/RubyBukkit.24899/
website-dev: http://dev.bukkit.org/server-mods/rubybukkit/
description: Loads Bukkit plugins made in Ruby
version: 0.7
